// Product data we want to CREATE via Flex API (what we SEND to Flex)
export type ProductToCreate = {
  name: string;
  description?: string;
  upc_code?: string;
  gtin?: string;
  reference_gtin?: string;
  visit_type?: "cbtSleep" | "fitness" | "nutrition" | "wellness";
  url?: string;
  hsa_fsa_eligibility?: "not_eligible" | "eligible" | "lomn_required";
  metadata?: Record<string, unknown>;
  // Our e-commerce additions for display (not sent to Flex)
  price: number;
  image: string;
};

// Product data we GET BACK from Flex after creating (what Flex RETURNS)
export type FlexProduct = {
  product_id: string; // Generated by Flex
  name: string;
  description?: string;
  created_at: string; // Generated by Flex
  visit_type?: "cbtSleep" | "fitness" | "nutrition" | "wellness";
  active: boolean; // Generated by Flex (defaults to true)
  upc_code?: string;
  gtin?: string;
  reference_gtin?: string;
  hsa_fsa_eligibility?: "not_eligible" | "eligible" | "lomn_required";
  test_mode: boolean; // Generated by Flex
  metadata?: Record<string, unknown>;
  url?: string;
};
