import { ProductToCreate } from "@/types/product";

// Sample products data - what we want to CREATE via Flex API
// These would be sent to POST /v1/products to create them in Flex
// After creation, Flex would return these same objects with added fields like:
// - product_id (generated by Flex)
// - created_at (timestamp)
// - active (defaults to true)
// - test_mode (based on your API key)
export const products: ProductToCreate[] = [
  {
    name: "Fitness Resistance Bands",
    description:
      "Professional grade resistance bands for physical therapy and exercise.",
    upc_code: "123456789012",
    gtin: "01234567890123",
    visit_type: "fitness",
    hsa_fsa_eligibility: "eligible",
    metadata: {
      category: "Fitness",
    },
    price: 29.99,
    image: "/next.svg",
  },
  {
    name: "Digital Blood Pressure Monitor",
    description:
      "FDA approved digital blood pressure monitor with memory storage.",
    upc_code: "234567890123",
    gtin: "12345678901234",
    visit_type: "wellness",
    hsa_fsa_eligibility: "eligible",
    metadata: {
      category: "Health Monitoring",
    },
    price: 49.99,
    image: "/next.svg",
  },
  {
    name: "Yoga Mat with Alignment Lines",
    description: "Premium yoga mat designed for physical therapy and exercise.",
    upc_code: "345678901234",
    gtin: "23456789012345",
    visit_type: "fitness",
    hsa_fsa_eligibility: "lomn_required",
    metadata: {
      category: "Fitness",
    },
    price: 39.99,
    image: "/next.svg",
  },
  {
    name: "Sunscreen SPF 50",
    description: "Broad spectrum sunscreen protection, HSA/FSA eligible.",
    upc_code: "456789012345",
    gtin: "34567890123456",
    visit_type: "wellness",
    hsa_fsa_eligibility: "eligible",
    metadata: {
      category: "Personal Care",
    },
    price: 12.99,
    image: "/next.svg",
  },
];
